export const venueList = [
  {
    id: 1,
    name: "One Eyed Jacques",
    image: "C:UserscraigOneDriveDocumentsDanceCardDanceCardassetsOEJ.png",
    address: "3104 W Cary Street",
    city: "Richmond",
    state: "VA",
    postalCode: "23221",
    email: "oej.contact@gmail.com",
    website: "oneeyedjacques.com",
    hours: {
      sun: "11-9",
      mon: "11-9",
      tues: "11-9",
      wed: "11-9",
      thurs: "11-9",
      fri: "11-9",
      sat: "11-9",
    },
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
  },
  {
    id: 2,
    name: "Battlegrounds",
    image:
      "C:UserscraigOneDriveDocumentsDanceCardDanceCardassets\battlegrounds.jpg",
    address: "13172 Midlothian TPKE",
    city: "Midlothian",
    state: "VA",
    postalCode: "23113",
    email: "something@battlegrounds.com",
    website: "battlegroundsrva.com",
    hours: {
      sun: "11-9",
      mon: "11-9",
      tues: "11-9",
      wed: "11-9",
      thurs: "11-9",
      fri: "11-9",
      sat: "11-9",
    },
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
  },
  {
    id: 3,
    name: "Tower of Games",
    image:
      "C:UserscraigOneDriveDocumentsDanceCardDanceCardassets\towerofgames.png",
    address: "5405 Indian River Rd Ste A",
    city: "Viginia Beach",
    state: "VA",
    postalCode: "23464",
    email: "something@towerofgames.com",
    website: "towerofgames.com",
    hours: {
      sun: "11-9",
      mon: "11-9",
      tues: "11-9",
      wed: "11-9",
      thurs: "11-9",
      fri: "11-9",
      sat: "11-9",
    },
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
  },
];
