export const venueList = [
  {
    id: 1,
    name: "One Eyed Jacques",
    image: require("../../assets/OEJ.png"),
    address: "3104 W Cary Street",
    city: "Richmond",
    state: "VA",
    postalCode: "23221",
    email: "oej.contact@gmail.com",
    website: "oneeyedjacques.com",
    hours: {
      sun: "11-9",
      mon: "11-9",
      tues: "11-9",
      wed: "11-9",
      thurs: "11-9",
      fri: "11-9",
      sat: "11-9",
    },
    phone: "804 359-5163",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 2,
    name: "Battlegrounds",
    image: require("../../assets/battlegrounds.jpg"),
    address: "13172 Midlothian TPKE",
    city: "Midlothian",
    state: "VA",
    postalCode: "23113",
    email: "something@battlegrounds.com",
    website: "battlegroundsrva.com",
    hours: {
      sun: "11-10",
      mon: "11-10",
      tues: "11-10",
      wed: "11-10",
      thurs: "11-11",
      fri: "11-10",
      sat: "11-12",
    },
    phone: "804 359-1111",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 3,
    name: "Tower of Games",
    image: require("../../assets/towerofgames.png"),
    address: "5405 Indian River Rd Ste A",
    city: "Viginia Beach",
    state: "VA",
    postalCode: "23464",
    email: "something@towerofgames.com",
    website: "towerofgames.com",
    hours: {
      sun: "12-9",
      mon: "12-9",
      tues: "12-9",
      wed: "12-9",
      thurs: "12-9",
      fri: "12-9",
      sat: "12-9",
    },
    phone: "804 359-2222",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
